### ISSUE TITLE
Connection Error,  Connection aborted

### ISSUE THREAD

**Issue by mappjo** [sim0nx/python-openhab#11]
Connection between openHAB 2.5.0 Release Build on Raspberry pi and an other Raspberry pi with 
a Python 3 program aborted after hours.

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyCanTest_R.py", line 125, in <module>
    state=recv_Mess()    # initial state
  File "PyCanTest_R.py", line 114, in recv_Mess
    datWand(s,listTemp,"13FE04","Aussentemperatur: ")
  File "PyCanTest_R.py", line 78, in datWand
    AussentpRoh.state = WertI
  File "/home/pi/.local/lib/python3.5/site-packages/openhab/items.py", line 76, in state
    self.update(value)
  File "/home/pi/.local/lib/python3.5/site-packages/openhab/items.py", line 131, in update
    self.openhab.req_put('/items/{}/state'.format(self.name), data=v)
  File "/home/pi/.local/lib/python3.5/site-packages/openhab/client.py", line 134, in req_put
    r = self.session.put(self.base_url + uri_path, data=data, timeout=self.timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by mappjo** [comment]
Is there a way for try: except:  to prevent the program from crashing.
 After that retry  setting the Value AussentpRoh.state = WertI. and go on.

**Comment by sim0nx** [comment]
This is not something I think that should be handled by the library, but instead should be handled in your code. As you suggest, I would use try-except to catch the error and try again or continue.

```
try:
  ...
except requests.exceptions.ConnectionError:
  ...
```

should do.

**Comment by mappjo** [comment]
thanks for the answer 
maybe the connection is really broken from time to time and i check the connection before i setting the state.

**Comment by sim0nx** [comment]
From the error you get, it really looks like that.
