### ISSUE TITLE
invocation fails

### ISSUE THREAD

**Issue by TheCranston** [sim0nx/python-openhab#5]
attempting to update a string via python:

Traceback (most recent call last):
  File "./readPower.py", line 3, in <module>
    from openhab import openHAB
  File "/usr/local/lib/python3.5/dist-packages/openhab/__init__.py", line 1, in <module>
    from .client import openHAB, OpenHAB
  File "/usr/local/lib/python3.5/dist-packages/openhab/client.py", line 30, in <module>
    import openhab.items
  File "/usr/local/lib/python3.5/dist-packages/openhab/items.py", line 34, in <module>
    class Item:
  File "/usr/local/lib/python3.5/dist-packages/openhab/items.py", line 78, in Item
    def _validate_value(self, value: typing.Union[str, typing.Type[openhab.types.CommandType]]):
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

Script in use, based on examples:

`#! /usr/bin/python3

from openhab import openHAB
import urllib
import socket
import time

base_url = 'http://localhost:8080/rest'
openhab = openHAB(base_url)

timeout = 20
socket.setdefaulttimeout(timeout)

link = "http://192.168.1.1/instantaneousdemand"

while True:
    try:
        myitem = openhab.get_item("InstantPowerConsumption")
        f = urllib.urlopen(link)
        myfile = f.read()
        if myfile != "000000.000 kW":
            myitem.state = myfile
        time.sleep(10)
    except:
        time.sleep(10)
`

**Comment by sim0nx** [comment]
I suspect this to be related to the "typing" module but I am not really sure what the problem here is. I can't reproduce your errors
